import { PGlite } from "@electric-sql/pglite";
import { readFileSync } from "node:fs";
import assert from "node:assert/strict";
const db = new PGlite();
await db.exec("create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;");
await db.exec(readFileSync("supabase/player-social.sql","utf8"));
await db.exec(readFileSync("supabase/duo-history.sql","utf8"));
const [owner,guest,other]=[crypto.randomUUID(),crypto.randomUUID(),crypto.randomUUID()];
for(const id of [owner,guest,other]) await db.query("insert into auth.users values($1)",[id]);
const as=async id=>{await db.exec("set role authenticated");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);};
const list=async()=> (await db.query("select public.list_dilemma_duos() as data")).rows[0].data;
await as(owner);
const code=(await db.query("select public.create_dilemma_duel($1,$2) as code",[JSON.stringify(["a","b","c","d","e"]),JSON.stringify([0,1,0,1,0])])).rows[0].code;
assert.equal((await list())[0].code,code);
await as(other); assert.deepEqual(await list(),[]);
await as(guest);
await db.query("select public.answer_dilemma_duel($1,$2)",[code,JSON.stringify([0,1,0,1,0])]);
assert.equal((await list())[0].complete,true);
await db.exec("reset role");
await db.query("update public.dilemma_duels set expires_at=now()-interval '1 day' where code=$1",[code]);
await as(owner); assert.equal((await list())[0].expired,true);
await db.query("select public.read_dilemma_duel($1)",[code]);
await as(guest); await db.query("select public.read_dilemma_duel($1)",[code]);
await as(other); await assert.rejects(db.query("select public.read_dilemma_duel($1)",[code]));
await db.exec("set role anon"); await assert.rejects(db.query("select public.list_dilemma_duos()"));
await db.close();
console.log("Duo persistence, participant isolation and expired results passed.");
